### ISSUE TITLE
clear waypoint

### ISSUE THREAD

**Issue by SwissalpS** [OgelGames/tape_measure#1]
congrats, this is a long due and cool implementation.

I don't know how to clear the waypoint though, clicking the same spot did nothing. It would however be a way to do it.

**Comment by OgelGames** [comment]
You clear it by clicking nothing. I forgot to mention that in the readme sorry.

I think I'll add your suggestion though, makes sense.

**Comment by SwissalpS** [comment]
I was hoping clicking nothing would set a waypoint in mid-air and sneak clicking nothing start/stop measure.

But it's fine, as long as there is a way to clear the waypoint.
